"""Authoritative career intelligence data layer.

This module is the single source of truth for career profiles used by the
assessment, skill-gap analysis, roadmap, and career recommender.

The source CSV is generated by ``src/create_career_database.py`` and contains
career metadata plus the required skill profile for every supported career.
"""

from pathlib import Path
from typing import Optional

import pandas as pd


BASE_DIR = Path(__file__).resolve().parent.parent
CAREER_INTELLIGENCE_FILE = (
    BASE_DIR / "data" / "processed" / "career_intelligence.csv"
)


EXPECTED_COLUMNS = [
    "Career",
    "Career_Category",
    "Career_Description",
    "Skill",
    "Skill_Category",
    "Required_Level",
    "Importance",
]


def load_career_intelligence() -> pd.DataFrame:
    """Load and validate the authoritative career intelligence table."""

    if not CAREER_INTELLIGENCE_FILE.exists():
        raise FileNotFoundError(
            "Career intelligence database was not found at "
            f"{CAREER_INTELLIGENCE_FILE}. Run "
            "python src/create_career_database.py first."
        )

    df = pd.read_csv(CAREER_INTELLIGENCE_FILE)

    missing = [column for column in EXPECTED_COLUMNS if column not in df.columns]
    if missing:
        raise ValueError(
            "Career intelligence database is missing columns: "
            + ", ".join(missing)
        )

    if df.empty:
        raise ValueError("Career intelligence database is empty.")

    df["Required_Level"] = pd.to_numeric(
        df["Required_Level"], errors="coerce"
    ).fillna(0).astype(int).clip(0, 10)

    df["Importance"] = (
        df["Importance"].fillna("Important").astype(str).str.strip()
    )

    return df


def get_all_careers() -> list[str]:
    """Return all supported careers from the authoritative database."""

    df = load_career_intelligence()
    return sorted(df["Career"].dropna().unique().tolist())


def get_career_profile(career: str) -> Optional[list[dict]]:
    """Return the complete skill profile for one career."""

    if not career:
        return None

    df = load_career_intelligence()
    career_df = df[df["Career"].str.casefold() == career.casefold()].copy()

    if career_df.empty:
        return None

    columns = [
        "Career",
        "Career_Category",
        "Career_Description",
        "Skill",
        "Skill_Category",
        "Required_Level",
        "Importance",
    ]

    return career_df[columns].to_dict(orient="records")


def get_career_metadata(career: str) -> Optional[dict]:
    """Return career-level metadata for a selected career."""

    profile = get_career_profile(career)

    if not profile:
        return None

    first = profile[0]

    return {
        "career": first["Career"],
        "category": first["Career_Category"],
        "description": first["Career_Description"],
        "skill_count": len(profile),
        "critical_skill_count": sum(
            1 for skill in profile if skill["Importance"] == "Critical"
        ),
    }


def get_required_skills(career: str) -> dict[str, int]:
    """Return canonical required skill levels for a career."""

    profile = get_career_profile(career)

    if not profile:
        raise ValueError(f"Career '{career}' was not found.")

    return {
        item["Skill"]: int(item["Required_Level"])
        for item in profile
    }


def get_skill_requirements(career: str) -> list[dict]:
    """Return skill requirements including importance and categories."""

    profile = get_career_profile(career)

    if not profile:
        raise ValueError(f"Career '{career}' was not found.")

    return [
        {
            "skill": item["Skill"],
            "required_level": int(item["Required_Level"]),
            "importance": item["Importance"],
            "skill_category": item["Skill_Category"],
        }
        for item in profile
    ]
